# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-09 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamplePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('position', models.IntegerField()),
            ],
            options={
                'ordering': ('position',),
            },
        ),
    ]
